repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # Use the latest version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 22.3.0  # Use the latest version
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0  # Use the latest version
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-check-builtin-literals

  # For Jupyter Notebooks
  - repo: https://github.com/kynan/nbstripout
    rev: 0.3.9  # Use the latest version
    hooks:
      - id: nbstripout
