credentials:
  usernames:
    msidhu:
      email: msidhu861@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Manraj Sidhu
      password: password # Will be hashed automatically
cookie:
  expiry_days: 30
  key: "some_signature_key" # Must be string
  name: "some_cookie_name"
